# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "uriversal"
  s.version = "0.0.1.pre4"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Zeeraw"]
  s.date = "2011-12-31"
  s.description = ""
  s.email = "zeeraw@cloudsdale.org"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "lib/uriversal.rb",
    "lib/uriversal/defaults.rb",
    "lib/uriversal/registry.rb",
    "lib/uriversal/registry/domain.rb",
    "lib/uriversal/registry/file_type.rb",
    "lib/uriversal/registry/path.rb",
    "lib/uriversal/registry/query.rb",
    "lib/uriversal/response.rb",
    "lib/uriversal/strategy.rb",
    "lib/uriversal/url.rb",
    "lib/uriversal/version.rb",
    "spec/spec_helper.rb",
    "spec/uriversal/registry/domain_spec.rb",
    "spec/uriversal/registry/file_type_spec.rb",
    "spec/uriversal/registry/path_spec.rb",
    "spec/uriversal/registry_spec.rb",
    "spec/uriversal/strategy_spec.rb",
    "spec/uriversal/url_spec.rb",
    "spec/uriversal_spec.rb",
    "uriversal.gemspec"
  ]
  s.homepage = "http://github.com/IOMUSE/Uriversal"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "A gem with main purpose to fetch information through a supplied url and return it in a nice standardized package."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<addressable>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["= 1.1.rc"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
    else
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<addressable>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, ["= 1.1.rc"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
    end
  else
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<addressable>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, ["= 1.1.rc"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
  end
end

